name: Deploy Vite + Vue to GitHub Pages

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PC/frontend/virtual-charac-commu-app  

    steps:
      # 检出仓库代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: PC/frontend/virtual-charac-commu-app/package-lock.json

      # 安装依赖 & 打包
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PC/frontend/virtual-charac-commu-app/dist  
